<a href="https://www.bigdatauniversity.com"><img src = "https://ibm.box.com/shared/static/jvcqp2iy2jlx2b32rmzdt0tx8lvxgzkp.png" width = 300, align = "center"></a>


# <center> Text generation using RNN/LSTM (Character-level)</center>

<div class="alert alert-block alert-info">
<font size = 3><strong>In this notebook you will learn the How to use TensorFlow for create a Recurrent Neural Network</strong></font>
<br>    
- <a href="#intro">Introduction</a>
<br>
- <p><a href="#arch">Architectures</a></p>
    - <a href="#lstm">Long Short-Term Memory Model (LSTM)</a>

- <p><a href="#build">Building a LSTM with TensorFlow</a></p>
</div>
----------------

This code implements a Recurrent Neural Network with LSTM/RNN units for training/sampling from character-level language models. In other words, the model takes a text file as input and trains the RNN network that learns to predict the next character in a sequence.  
The RNN can then be used to generate text character by character that will look like the original training data. 

This code is based on this [blog](http://karpathy.github.io/2015/05/21/rnn-effectiveness/), and the code is an step-by-step implimentation of the [character-level implimentation](https://github.com/crazydonkey200/tensorflow-char-rnn).




First, import the requiered libraries:

In [6]:
import tensorflow as tf
import time
import codecs
import os
import collections
from six.moves import cPickle
import numpy as np
#from tensorflow.python.ops import rnn_cell
#from tensorflow.python.ops import seq2seq

### Data loader
The following cell is a class that help to read data from input file.

In [7]:
class TextLoader():
    def __init__(self, data_dir, batch_size, seq_length, encoding='utf-8'):
        self.data_dir = data_dir
        self.batch_size = batch_size
        self.seq_length = seq_length
        self.encoding = encoding

        input_file = os.path.join(data_dir, "input.txt")
        vocab_file = os.path.join(data_dir, "vocab.pkl")
        tensor_file = os.path.join(data_dir, "data.npy")

        if not (os.path.exists(vocab_file) and os.path.exists(tensor_file)):
            print("reading text file")
            self.preprocess(input_file, vocab_file, tensor_file)
        else:
            print("loading preprocessed files")
            self.load_preprocessed(vocab_file, tensor_file)
        self.create_batches()
        self.reset_batch_pointer()

    def preprocess(self, input_file, vocab_file, tensor_file):
        with codecs.open(input_file, "r", encoding=self.encoding) as f:
            data = f.read()
        counter = collections.Counter(data)
        count_pairs = sorted(counter.items(), key=lambda x: -x[1])
        self.chars, _ = zip(*count_pairs)
        self.vocab_size = len(self.chars)
        self.vocab = dict(zip(self.chars, range(len(self.chars))))
        with open(vocab_file, 'wb') as f:
            cPickle.dump(self.chars, f)
        self.tensor = np.array(list(map(self.vocab.get, data)))
        np.save(tensor_file, self.tensor)

    def load_preprocessed(self, vocab_file, tensor_file):
        with open(vocab_file, 'rb') as f:
            self.chars = cPickle.load(f)
        self.vocab_size = len(self.chars)
        self.vocab = dict(zip(self.chars, range(len(self.chars))))
        self.tensor = np.load(tensor_file)
        self.num_batches = int(self.tensor.size / (self.batch_size * self.seq_length))

    def create_batches(self):
        self.num_batches = int(self.tensor.size / (self.batch_size * self.seq_length))

        # When the data (tensor) is too small, let's give them a better error message
        if self.num_batches==0:
            assert False, "Not enough data. Make seq_length and batch_size small."

        self.tensor = self.tensor[:self.num_batches * self.batch_size * self.seq_length]
        xdata = self.tensor
        ydata = np.copy(self.tensor)
        ydata[:-1] = xdata[1:]
        ydata[-1] = xdata[0]
        self.x_batches = np.split(xdata.reshape(self.batch_size, -1), self.num_batches, 1)
        self.y_batches = np.split(ydata.reshape(self.batch_size, -1), self.num_batches, 1)


    def next_batch(self):
        x, y = self.x_batches[self.pointer], self.y_batches[self.pointer]
        self.pointer += 1
        return x, y

    def reset_batch_pointer(self):
        self.pointer = 0

### Parameters
#### Batch, number_of_batch, batch_size and seq_length
what is batch, number_of_batch, batch_size and seq_length in the charcter level example?  

Lets assume the input is this sentence: '__here is an example__'. Then:
- txt_length = 18  
- seq_length = 3  
- batch_size = 2  
- number_of_batchs = 18/3*2 = 3
- batch = array (['h','e','r'],['e',' ','i'])
- sample Seq = 'her'  

Ok, now, lets look at a real dataset, with real parameters. 

In [8]:
seq_length = 50 # RNN sequence length
batch_size = 60  # minibatch size, i.e. size of data in each epoch
num_epochs = 125 # you should change it to 50 if you want to see a relatively good results
learning_rate = 0.002
decay_rate = 0.97
rnn_size = 128 # size of RNN hidden state (output dimension)
num_layers = 2 #number of layers in the RNN

We download the input file, and print a part of it:

In [9]:
!wget -nv -O input.txt https://ibm.box.com/shared/static/a3f9e9mbpup09toq35ut7ke3l3lf03hg.txt 
with open('input.txt', 'r') as f:
    read_data = f.read()
    print read_data[0:100]
f.closed

2017-08-27 09:52:06 URL:https://public.boxcloud.com/d/1/h5UrJegTgokUg8yVyOCZcAuE6H6f9YYTpXtAmFq5AWkvpY-3TVBUocRRxitYu_sI21b8Zp03enbeGItOIjMhdicEL4OQGxme8e6B5STzls8WvTfQ05gRRtVuFTFme-u5USK6jUHYoHibZepuU941VXIhTqhzYvC9To1v3yEgrwVayUzlklMACnXT9S2XU1bo9QrwBiBfRq3eRQSPSRCTRtg4L1Mqt2_OfdYpV0mbWnup9uA4aC1XxUfzMHgnMwlXg5A4RXal593YkkI99YKpH00S_pzBjW1kFuzvEsBVwGlM4uk8SkiuAq1Ru1rXspAHixzm3xikAYUv5VTbkoc8Ks2ZNqVQz5VVyGycyGtnNREne3PQW-qDDjSmfgDwC_aJHuikWsu1ARgQmLgkfIXRo23K6Z969SqnVraTkB-P68vWbq_3rAuo5vucWuFKXaOnWY60mno_-QDnomVp8hrW_HtgmHuwWH9xLg2VQD-nDyd6j6gp09pcSt_LItU8O6FlmLSXH9ytM2nOQUrnksGKVfWZ6ajiX66-AD6G80igfKspNpwOttaop_zo73GlHaRgyn_h7SUQOg_2AX9n_UvNQq6bipsxGlWUkQh4wD6-zaRHpNxbZ5KoBWcNFwhf5r0NWMglT5zVaxs0Bu-pUb6sp52QTOGGOao24eO4Z29V5yirMYFnQeEJZxztOdqe23vF_1dk27BuLLlcfTAHUZtVLcDNZd7RRo_eKxejbvp4pnd4ugAkfUgwv-Dh8joXdMK1Ol7l-RLugTcuDJVj_hFsaFCsWH4q7JhZlMl2ObuWRZAoG4Ji-BC_zF_cRh2wsjceNjboUCCYhcteCr99daGTBspJ7VatHk15XcVmTY5I_9_1_aukdus0Hip2yVZJ-hI6tX-6sJQc9F501FURcXBO9kAbFsyY6YkvpOxtv2ESYrLjhLc3

True

Now, we can read the data at batches using the __TextLoader__ class. It will convert the characters to numbers, and represent each sequence as a vector in batches:

In [10]:
data_loader = TextLoader('', batch_size, seq_length)
vocab_size = data_loader.vocab_size
print "vocabulary size:" ,data_loader.vocab_size
print "Characters:" ,data_loader.chars
print "vocab number of 'F':",data_loader.vocab['F']
print "Character sequences (first batch):", data_loader.x_batches[0]

reading text file
vocabulary size: 65
Characters: (u' ', u'e', u't', u'o', u'a', u'h', u's', u'r', u'n', u'i', u'\n', u'l', u'd', u'u', u'm', u'y', u',', u'w', u'f', u'c', u'g', u'I', u'b', u'p', u':', u'.', u'A', u'v', u'k', u'T', u"'", u'E', u'O', u'N', u'R', u'S', u'L', u'C', u';', u'W', u'U', u'H', u'M', u'B', u'?', u'G', u'!', u'D', u'-', u'F', u'Y', u'P', u'K', u'V', u'j', u'q', u'x', u'z', u'J', u'Q', u'Z', u'X', u'3', u'&', u'$')
vocab number of 'F': 49
Character sequences (first batch): [[49  9  7 ...,  1  4  7]
 [19  4 14 ..., 14  9 20]
 [ 8 20 10 ...,  8 10 18]
 ..., 
 [21  2  0 ...,  0 21  0]
 [ 9  7  7 ...,  0  2  3]
 [ 3  7  0 ...,  5  9 23]]


### Input and output

In [11]:
x,y = data_loader.next_batch()
x

array([[49,  9,  7, ...,  1,  4,  7],
       [19,  4, 14, ..., 14,  9, 20],
       [ 8, 20, 10, ...,  8, 10, 18],
       ..., 
       [21,  2,  0, ...,  0, 21,  0],
       [ 9,  7,  7, ...,  0,  2,  3],
       [ 3,  7,  0, ...,  5,  9, 23]])

In [12]:
x.shape  #batch_size =60, seq_length=50

(60, 50)

Here, __y__ is the next character for each character in __x__:

In [13]:
y

array([[ 9,  7,  6, ...,  4,  7,  0],
       [ 4, 14, 22, ...,  9, 20,  5],
       [20, 10, 29, ..., 10, 18,  4],
       ..., 
       [ 2,  0,  6, ..., 21,  0,  6],
       [ 7,  7,  4, ...,  2,  3,  0],
       [ 7,  0, 33, ...,  9, 23,  0]])

### LSTM Architecture
Each LSTM cell has 5 parts:
1. Input
2. prv_state
3. prv_output
4. new_state
5. new_output


- Each LSTM cell has an input layre, which its size is 128 units in our case. The input vector's dimension also is 128, which is the dimensionality of embedding vector, so called, dimension size of W2V/embedding, for each character/word.
- Each LSTM cell has a hidden layer, where there are some hidden units. The argument n_hidden=128 of BasicLSTMCell is the number of hidden units of the LSTM (inside A). It keeps the size of the output and state vector. It is also known as, rnn_size, num_units, num_hidden_units, and LSTM size
- An LSTM keeps two pieces of information as it propagates through time: 
    - __hidden state__ vector: Each LSTM cell accept a vector, called __hidden state__ vector, of size n_hidden=128, and its value is returned to the LSTM cell in the next step. The __hidden state__ vector; which is the memory of the LSTM, accumulates using its (forget, input, and output) gates through time. "num_units" is equivalant to "size of RNN hidden state". number of hidden units is the dimensianality of the output (= dimesianality of the state) of the LSTM cell.
    - __previous time-step output__: For each LSTM cell that we initialize, we need to supply a value (128 in this case) for the hidden dimension, or as some people like to call it, the number of units in the LSTM cell. 


#### num_layers = 2 
- number of layers in the RNN, is defined by num_layers
- An input of MultiRNNCell is __cells__ which is list of RNNCells that will be composed in this order.

### Defining stacked RNN Cell

__BasicRNNCell__ is the most basic RNN cell.

In [14]:
cell = tf.contrib.rnn.BasicRNNCell(rnn_size)

In [15]:
# a two layer cell
stacked_cell = tf.contrib.rnn.MultiRNNCell([cell] * num_layers)

In [16]:
# hidden state size
stacked_cell.output_size

128

__state__ varibale keeps output and new_state of the LSTM, so it is a touple of size:

In [17]:
stacked_cell.state_size

(128, 128)

Lets define input data:

In [18]:
input_data = tf.placeholder(tf.int32, [batch_size, seq_length])# a 60x50
input_data

<tf.Tensor 'Placeholder:0' shape=(60, 50) dtype=int32>

and target data:

In [19]:
targets = tf.placeholder(tf.int32, [batch_size, seq_length]) # a 60x50
targets

<tf.Tensor 'Placeholder_1:0' shape=(60, 50) dtype=int32>

The memory state of the network is initialized with a vector of zeros and gets updated after reading each character.

__BasicRNNCell.zero_state(batch_size, dtype)__ Return zero-filled state tensor(s). In this function, batch_size
representing the batch size.

In [20]:
initial_state = stacked_cell.zero_state(batch_size, tf.float32) #why batch_size ? 60x128

Lets check the value of the input_data again:

In [21]:
session = tf.Session()
feed_dict={input_data:x, targets:y}
session.run(input_data, feed_dict)

array([[49,  9,  7, ...,  1,  4,  7],
       [19,  4, 14, ..., 14,  9, 20],
       [ 8, 20, 10, ...,  8, 10, 18],
       ..., 
       [21,  2,  0, ...,  0, 21,  0],
       [ 9,  7,  7, ...,  0,  2,  3],
       [ 3,  7,  0, ...,  5,  9, 23]], dtype=int32)

### Embedding
In this section, we build a 128-dim vector for each character. As we have 60 batches, and 50 character in each sequence, it will generate a [60,50,128] matrix.

__Notice:__ The function `tf.get_variable()` is used to share a variable and to initialize it in one place. `tf.get_variable()` is used to get or create a variable instead of a direct call to `tf.Variable`. 

In [22]:
with tf.variable_scope('rnnlm', reuse=False):
    softmax_w = tf.get_variable("softmax_w", [rnn_size, vocab_size]) #128x65
    softmax_b = tf.get_variable("softmax_b", [vocab_size]) # 1x65)
    #with tf.device("/cpu:0"):
        
    # embedding variable is initialized randomely
    embedding = tf.get_variable("embedding", [vocab_size, rnn_size])  #65x128

    # embedding_lookup goes to each row of input_data, and for each character in the row, finds the correspond vector in embedding
    # it creates a 60*50*[1*128] matrix
    # so, the first elemnt of em, is a matrix of 50x128, which each row of it is vector representing that character
    em = tf.nn.embedding_lookup(embedding, input_data) # em is 60x50x[1*128]
    # split: Splits a tensor into sub tensors.
    # syntax:  tf.split(split_dim, num_split, value, name='split')
    # it will split the 60x50x[1x128] matrix into 50 matrix of 60x[1*128]
    inputs = tf.split(em, seq_length, 1)
    # It will convert the list to 50 matrix of [60x128]
    inputs = [tf.squeeze(input_, [1]) for input_ in inputs]

Lets take a look at the __embedding__, __em__, and __inputs__ variabbles:

Embedding variable is initialized with random values:

In [23]:
session.run(tf.global_variables_initializer())
#print embedding.shape
session.run(embedding)

array([[-0.03740785, -0.08024105,  0.10276715, ...,  0.00965647,
        -0.08643632,  0.00621697],
       [ 0.10739483, -0.1623219 , -0.10691629, ...,  0.01649493,
        -0.08520067, -0.05544248],
       [ 0.02221389, -0.05994718,  0.07511498, ..., -0.01980883,
        -0.15673512, -0.08660065],
       ..., 
       [ 0.1514294 , -0.03491271,  0.02888335, ...,  0.15929399,
         0.04341963,  0.12477018],
       [-0.05201239, -0.02715965,  0.11330606, ..., -0.0200846 ,
         0.04034892, -0.14396353],
       [ 0.09361865,  0.04710871, -0.17496687, ...,  0.00483717,
        -0.16253099, -0.08400996]], dtype=float32)

The first elemnt of em, is a matrix of 50x128, which each row of it is vector representing that character

In [24]:
em = tf.nn.embedding_lookup(embedding, input_data)
emp = session.run(em,feed_dict={input_data:x})
print emp.shape
emp[0]

(60, 50, 128)


array([[ 0.10305618,  0.13517584, -0.00317685, ...,  0.02965444,
        -0.05014209, -0.11718509],
       [-0.05303945,  0.15498324,  0.06280427, ..., -0.17578092,
        -0.00654107, -0.0120651 ],
       [ 0.09004374,  0.06086949,  0.00781377, ...,  0.15489723,
        -0.06277904,  0.00843377],
       ..., 
       [ 0.10739483, -0.1623219 , -0.10691629, ...,  0.01649493,
        -0.08520067, -0.05544248],
       [ 0.08668901,  0.03473888,  0.1626638 , ..., -0.16189614,
        -0.08235044,  0.09670912],
       [ 0.09004374,  0.06086949,  0.00781377, ...,  0.15489723,
        -0.06277904,  0.00843377]], dtype=float32)

Let's consider each sequence as a sentence of length 50 characters, then, the first item in __inputs__ is a [60x128] vector which represents the first characters of 60 sentences.

In [25]:
inputs = tf.split(em, seq_length, 1)
inputs = [tf.squeeze(input_, [1]) for input_ in inputs]
inputs[0:5]

[<tf.Tensor 'Squeeze:0' shape=(60, 128) dtype=float32>,
 <tf.Tensor 'Squeeze_1:0' shape=(60, 128) dtype=float32>,
 <tf.Tensor 'Squeeze_2:0' shape=(60, 128) dtype=float32>,
 <tf.Tensor 'Squeeze_3:0' shape=(60, 128) dtype=float32>,
 <tf.Tensor 'Squeeze_4:0' shape=(60, 128) dtype=float32>]

### Feeding a batch of 50 sequence to a RNN:

The feeding process for iputs is as following:

- Step 1:  first character of each of the 50 sentences (in a batch) is entered in parallel.  
- Step 2:  second character of each of the 50 sentences is input in parallel. 
- Step n: nth character of each of the 50 sentences is input in parallel.  

The parallelism is only for efficiency.  Each character in a batch is handled in parallel,  but the network sees one character of a sequence at a time and does the computations accordingly. All the computations involving the characters of all sequences in a batch at a given time step are done in parallel. 

In [26]:
session.run(inputs[0],feed_dict={input_data:x})

array([[ 0.10305618,  0.13517584, -0.00317685, ...,  0.02965444,
        -0.05014209, -0.11718509],
       [-0.10395588, -0.09172855, -0.15021645, ...,  0.02156794,
        -0.09225049,  0.04857115],
       [ 0.09296091, -0.07455122,  0.06394549, ..., -0.06698208,
        -0.08926528, -0.01145135],
       ..., 
       [ 0.00028959, -0.16052178,  0.09523468, ..., -0.08286103,
        -0.02855912,  0.12375255],
       [-0.05303945,  0.15498324,  0.06280427, ..., -0.17578092,
        -0.00654107, -0.0120651 ],
       [-0.1435257 ,  0.14510982, -0.12893906, ..., -0.07617413,
        -0.03457804, -0.06249297]], dtype=float32)

Feeding the RNN with one batch, we can check the new output and new state of network:

In [27]:
#outputs is 50x[60*128]
outputs, new_state = tf.contrib.legacy_seq2seq.rnn_decoder(inputs, initial_state, stacked_cell, loop_function=None, scope='rnnlm')
new_state

(<tf.Tensor 'rnnlm_1/rnnlm/multi_rnn_cell/cell_0/cell_0/basic_rnn_cell/Tanh_98:0' shape=(60, 128) dtype=float32>,
 <tf.Tensor 'rnnlm_1/rnnlm/multi_rnn_cell/cell_0/cell_0/basic_rnn_cell/Tanh_99:0' shape=(60, 128) dtype=float32>)

In [28]:
outputs[0:5]

[<tf.Tensor 'rnnlm_1/rnnlm/multi_rnn_cell/cell_0/cell_0/basic_rnn_cell/Tanh_1:0' shape=(60, 128) dtype=float32>,
 <tf.Tensor 'rnnlm_1/rnnlm/multi_rnn_cell/cell_0/cell_0/basic_rnn_cell/Tanh_3:0' shape=(60, 128) dtype=float32>,
 <tf.Tensor 'rnnlm_1/rnnlm/multi_rnn_cell/cell_0/cell_0/basic_rnn_cell/Tanh_5:0' shape=(60, 128) dtype=float32>,
 <tf.Tensor 'rnnlm_1/rnnlm/multi_rnn_cell/cell_0/cell_0/basic_rnn_cell/Tanh_7:0' shape=(60, 128) dtype=float32>,
 <tf.Tensor 'rnnlm_1/rnnlm/multi_rnn_cell/cell_0/cell_0/basic_rnn_cell/Tanh_9:0' shape=(60, 128) dtype=float32>]

Let's check the output of network after feeding it with first batch:

In [29]:
first_output = outputs[0]
session.run(tf.global_variables_initializer())
session.run(first_output,feed_dict={input_data:x})

array([[ -1.06913503e-02,   8.50840881e-02,  -6.88443929e-02, ...,
         -1.15907021e-01,   4.39442694e-02,   1.49685636e-01],
       [ -7.71226734e-03,  -3.39723490e-02,  -5.48176422e-06, ...,
          3.10104433e-02,  -4.61876690e-02,   2.02981755e-01],
       [  8.16150829e-02,   2.66363117e-04,   1.02987222e-03, ...,
         -5.69967814e-02,   6.15253709e-02,  -1.96086243e-02],
       ..., 
       [  3.68828923e-02,   4.56273109e-02,  -9.39012542e-02, ...,
         -1.79064840e-01,   6.20441921e-02,  -6.02412634e-02],
       [ -8.52239132e-02,   5.78153245e-02,   1.10429473e-01, ...,
         -8.64275098e-02,   1.31150648e-01,  -1.33810237e-01],
       [ -1.06245995e-01,   4.55156155e-02,  -6.68492913e-02, ...,
         -1.86091252e-02,  -5.19520557e-03,  -2.76371222e-02]], dtype=float32)

As it was explained, __outputs__ variable is a 50x[60x128] tensor. We need to reshape it back to [60x50x128] to be able to calculate the probablity of the next character using the softmax. The __softmax_w__ shape is [rnn_size, vocab_size],whihc is [128x65] in our case. Threfore, we have a fully connected layer on top of LSTM cells, which help us to decode the next charachter. We can use the __softmax(output * softmax_w + softmax_b)__ for this purpose. The shape of the matrixis would be:

softmax([60x50x128]x[128x65]+[1x65]) = [60x50x65]

We can do it step-by-step:

In [30]:
output = tf.reshape(tf.concat( outputs,1), [-1, rnn_size])
output

<tf.Tensor 'Reshape:0' shape=(3000, 128) dtype=float32>

In [31]:
logits = tf.matmul(output, softmax_w) + softmax_b
logits

<tf.Tensor 'add:0' shape=(3000, 65) dtype=float32>

In [32]:
probs = tf.nn.softmax(logits)
probs

<tf.Tensor 'Softmax:0' shape=(3000, 65) dtype=float32>

Here is the probablity of the next chracter in all batches:

In [33]:
session.run(tf.global_variables_initializer())
session.run(probs,feed_dict={input_data:x})

array([[ 0.01827273,  0.01951737,  0.01238691, ...,  0.01707285,
         0.01495539,  0.01850691],
       [ 0.01733118,  0.01708234,  0.01168153, ...,  0.01670184,
         0.01800174,  0.0208231 ],
       [ 0.01779648,  0.01771784,  0.01582947, ...,  0.01491454,
         0.01302176,  0.0166511 ],
       ..., 
       [ 0.01921272,  0.01937138,  0.0142415 , ...,  0.01658666,
         0.01798107,  0.01750529],
       [ 0.01769108,  0.02304364,  0.01107922, ...,  0.015075  ,
         0.01597399,  0.01292654],
       [ 0.01702942,  0.01733125,  0.0123488 , ...,  0.01532995,
         0.01170009,  0.02112499]], dtype=float32)

Now, we are in the position to calculate the cost of training with __loss function__, and keep feedng the network to learn it. But, the question is: what the LSTM networks learn?

In [34]:
grad_clip =5.
tvars = tf.trainable_variables()
tvars

[<tf.Variable 'rnnlm/softmax_w:0' shape=(128, 65) dtype=float32_ref>,
 <tf.Variable 'rnnlm/softmax_b:0' shape=(65,) dtype=float32_ref>,
 <tf.Variable 'rnnlm/embedding:0' shape=(65, 128) dtype=float32_ref>,
 <tf.Variable 'rnnlm/multi_rnn_cell/cell_0/basic_rnn_cell/kernel:0' shape=(256, 128) dtype=float32_ref>,
 <tf.Variable 'rnnlm/multi_rnn_cell/cell_0/basic_rnn_cell/bias:0' shape=(128,) dtype=float32_ref>]

# All together
Now, let's put all of parts together in a class, and train the model:

In [35]:
class LSTMModel():
    def __init__(self,sample=False):
        rnn_size = 128 # size of RNN hidden state vector
        batch_size = 60 # minibatch size, i.e. size of dataset in each epoch
        seq_length = 50 # RNN sequence length
        num_layers = 2 # number of layers in the RNN
        vocab_size = 65
        grad_clip = 5.
        if sample:
            print(">> sample mode:")
            batch_size = 1
            seq_length = 1
        # The core of the model consists of an LSTM cell that processes one char at a time and computes probabilities of the possible continuations of the char. 
        basic_cell = tf.contrib.rnn.BasicRNNCell(rnn_size)
        # model.cell.state_size is (128, 128)
        self.stacked_cell = tf.contrib.rnn.MultiRNNCell([basic_cell] * num_layers)

        self.input_data = tf.placeholder(tf.int32, [batch_size, seq_length], name="input_data")
        self.targets = tf.placeholder(tf.int32, [batch_size, seq_length], name="targets")
        # Initial state of the LSTM memory.
        # The memory state of the network is initialized with a vector of zeros and gets updated after reading each char. 
        self.initial_state = stacked_cell.zero_state(batch_size, tf.float32) #why batch_size

        with tf.variable_scope('rnnlm_class1'):
            softmax_w = tf.get_variable("softmax_w", [rnn_size, vocab_size]) #128x65
            softmax_b = tf.get_variable("softmax_b", [vocab_size]) # 1x65
            with tf.device("/cpu:0"):
                embedding = tf.get_variable("embedding", [vocab_size, rnn_size])  #65x128
                inputs = tf.split(tf.nn.embedding_lookup(embedding, self.input_data), seq_length, 1)
                inputs = [tf.squeeze(input_, [1]) for input_ in inputs]
                #inputs = tf.split(em, seq_length, 1)
                
                


        # The value of state is updated after processing each batch of chars.
        outputs, last_state = tf.contrib.legacy_seq2seq.rnn_decoder(inputs, self.initial_state, self.stacked_cell, loop_function=None, scope='rnnlm_class1')
        output = tf.reshape(tf.concat(outputs,1), [-1, rnn_size])
        self.logits = tf.matmul(output, softmax_w) + softmax_b
        self.probs = tf.nn.softmax(self.logits)
        loss = tf.contrib.legacy_seq2seq.sequence_loss_by_example([self.logits],
                [tf.reshape(self.targets, [-1])],
                [tf.ones([batch_size * seq_length])],
                vocab_size)
        self.cost = tf.reduce_sum(loss) / batch_size / seq_length
        self.final_state = last_state
        self.lr = tf.Variable(0.0, trainable=False)
        tvars = tf.trainable_variables()
        grads, _ = tf.clip_by_global_norm(tf.gradients(self.cost, tvars),grad_clip)
        optimizer = tf.train.AdamOptimizer(self.lr)
        self.train_op = optimizer.apply_gradients(zip(grads, tvars))
    
    
    def sample(self, sess, chars, vocab, num=200, prime='The ', sampling_type=1):
        state = sess.run(self.stacked_cell.zero_state(1, tf.float32))
        #print state
        for char in prime[:-1]:
            x = np.zeros((1, 1))
            x[0, 0] = vocab[char]
            feed = {self.input_data: x, self.initial_state:state}
            [state] = sess.run([self.final_state], feed)

        def weighted_pick(weights):
            t = np.cumsum(weights)
            s = np.sum(weights)
            return(int(np.searchsorted(t, np.random.rand(1)*s)))

        ret = prime
        char = prime[-1]
        for n in range(num):
            x = np.zeros((1, 1))
            x[0, 0] = vocab[char]
            feed = {self.input_data: x, self.initial_state:state}
            [probs, state] = sess.run([self.probs, self.final_state], feed)
            p = probs[0]

            if sampling_type == 0:
                sample = np.argmax(p)
            elif sampling_type == 2:
                if char == ' ':
                    sample = weighted_pick(p)
                else:
                    sample = np.argmax(p)
            else: # sampling_type == 1 default:
                sample = weighted_pick(p)

            pred = chars[sample]
            ret += pred
            char = pred
        return ret

### Creating the LSTM object
Now we create a LSTM model:

In [ ]:
with tf.variable_scope("rnn"):
    model = LSTMModel()

# Train usinng LSTMModel class
We can train our model through feeding batches:

In [ ]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for e in range(num_epochs): # num_epochs is 5 for test, but should be higher
        sess.run(tf.assign(model.lr, learning_rate * (decay_rate ** e)))
        data_loader.reset_batch_pointer()
        state = sess.run(model.initial_state) # (2x[60x128])
        for b in range(data_loader.num_batches): #for each batch
            start = time.time()
            x, y = data_loader.next_batch()
            feed = {model.input_data: x, model.targets: y, model.initial_state:state}
            train_loss, state, _ = sess.run([model.cost, model.final_state, model.train_op], feed)
            end = time.time()
        print("{}/{} (epoch {}), train_loss = {:.3f}, time/batch = {:.3f}" \
                .format(e * data_loader.num_batches + b, num_epochs * data_loader.num_batches, e, train_loss, end - start))
        with tf.variable_scope("rnn", reuse=True):
            sample_model = LSTMModel(sample=True)
            print sample_model.sample(sess, data_loader.chars , data_loader.vocab, num=50, prime='The ', sampling_type=1)
            print '----------------------------------'

370/46375 (epoch 0), train_loss = 1.926, time/batch = 0.042
>> sample mode:
The waun's cone tlih nTeee
I, Mrabe a chand whit mes g
----------------------------------
741/46375 (epoch 1), train_loss = 1.761, time/batch = 0.050
>> sample mode:
The cwife soned in thy fiold freen were you prich of w
----------------------------------
1112/46375 (epoch 2), train_loss = 1.681, time/batch = 0.043
>> sample mode:
The ath:
Anformain whictilg the right. Rame to night t
----------------------------------
1483/46375 (epoch 3), train_loss = 1.639, time/batch = 0.039
>> sample mode:
The aV how I spoky of the ready my from nofe hath no c
----------------------------------
1854/46375 (epoch 4), train_loss = 1.612, time/batch = 0.039
>> sample mode:
The first by them.

ELBARETH:
You comes!
Thy from that
----------------------------------
2225/46375 (epoch 5), train_loss = 1.594, time/batch = 0.043
>> sample mode:
The Lefomen ourselcious friends,
Come? how dotn your g
----------------------------------


18549/46375 (epoch 49), train_loss = 1.453, time/batch = 0.070
>> sample mode:
The Lrdy:
I have those have, thanks To her,
And in his
----------------------------------
18920/46375 (epoch 50), train_loss = 1.452, time/batch = 0.067
>> sample mode:
The Didus
Should have part part of any companion to st
----------------------------------
19291/46375 (epoch 51), train_loss = 1.451, time/batch = 0.073
>> sample mode:
The APpiachour borided,
Which you light.

GLOUCESTER:

----------------------------------
19662/46375 (epoch 52), train_loss = 1.451, time/batch = 0.069
>> sample mode:
The ERIZBY:
Farewell, crowns, which we know your outwa
----------------------------------
20033/46375 (epoch 53), train_loss = 1.450, time/batch = 0.067
>> sample mode:
The bear hath know,
Terrow deep
And not not be;
But I 
----------------------------------
20404/46375 (epoch 54), train_loss = 1.449, time/batch = 0.068
>> sample mode:
The ANgrance, sir.

First
Yet no, I Strevoses, faintly
---------------------

## Want to learn more?

Running deep learning programs usually needs a high performance platform. PowerAI speeds up deep learning and AI. Built on IBM's Power Systems, PowerAI is a scalable software platform that accelerates deep learning and AI with blazing performance for individual users or enterprises. The PowerAI platform supports popular machine learning libraries and dependencies including Tensorflow, Caffe, Torch, and Theano. You can download a [free version of PowerAI](https://cocl.us/ML0120EN_PAI).

Also, you can use Data Science Experience to run these notebooks faster with bigger datasets. Data Science Experience is IBM's leading cloud solution for data scientists, built by data scientists. With Jupyter notebooks, RStudio, Apache Spark and popular libraries pre-packaged in the cloud, DSX enables data scientists to collaborate on their projects without having to install anything. Join the fast-growing community of DSX users today with a free account at [Data Science Experience](https://cocl.us/ML0120EN_DSX)This is the end of this lesson. Hopefully, now you have a deeper and intuitive understanding regarding the LSTM model. Thank you for reading this notebook, and good luck on your studies.

### Thanks for completing this lesson!
Created by: <a href = "https://linkedin.com/in/saeedaghabozorgi"> Saeed Aghabozorgi </a></h4>
This code is based on this [blog](http://karpathy.github.io/2015/05/21/rnn-effectiveness/), and the code is an step-by-step implimentation of the [character-level implimentation](https://github.com/crazydonkey200/tensorflow-char-rnn).